#!/usr/bin/bash
# Run this script in the SOURCES folder:
# $ ./mk-tar
########################
# The git tag to use:
tag="2.4.1"
# The release suffix to use for the tree root and tar.gz filename: 
rel="2.4.1"
pkg="volk"
########################
if [[ -d $pkg ]]; then
cd $pkg
git pull || { echo "ERROR: git pull failed"; exit 1; }
cd ..
else
git clone https://github.com/gnuradio/$pkg.git || { echo "ERROR: git clone failed"; exit 1; }
fi

[[ -d $pkg-$rel ]] && rm -rf $pkg-$rel

cp -r $pkg $pkg-$rel || { echo "ERROR: dir copy failed"; exit 1; }

cd $pkg-$rel || { echo "ERROR: cd failed"; exit 1; }

git checkout v$tag > /dev/null 2>&1 || { echo "ERROR: git checkout tag failed"; exit 1; }

git submodule update --init --recursive || { echo "ERROR: submodule update failed"; exit 1; }

cd ..

tar --exclude-vcs -czf $pkg-$rel.tar.gz $pkg-$rel/ && echo "$pkg-$rel.tar.gz created" || { echo "ERROR: tar creation failed"; exit 1; }

rm -rf $pkg-$rel || { echo "ERROR: delete temporary tree failed"; exit 1; }











